version: "3.9"
services:
  backend_2:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://Weather99:chami1999928@weatherdb.kmumq9l.mongodb.net/?retryWrites=true&w=majority

  frontend_2:
    build: ./frontend
    ports:
      - "3000:3000"
